//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteDirector.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Box", Namespace="http://schemas.datacontract.org/2004/07/IRouteDirector")]
    [System.SerializableAttribute()]
    public partial class Box : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string barcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int lineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string barcode {
            get {
                return this.barcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.barcodeField, value) != true)) {
                    this.barcodeField = value;
                    this.RaisePropertyChanged("barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int line {
            get {
                return this.lineField;
            }
            set {
                if ((this.lineField.Equals(value) != true)) {
                    this.lineField = value;
                    this.RaisePropertyChanged("line");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int node {
            get {
                return this.nodeField;
            }
            set {
                if ((this.nodeField.Equals(value) != true)) {
                    this.nodeField = value;
                    this.RaisePropertyChanged("node");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISorting")]
    public interface ISorting {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorting/AddBox", ReplyAction="http://tempuri.org/ISorting/AddBoxResponse")]
        int AddBox(string barcode, int node, int line);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorting/AddBoxList", ReplyAction="http://tempuri.org/ISorting/AddBoxListResponse")]
        int AddBoxList(RouteDirector.ServiceReference1.Box[] boxList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISortingChannel : RouteDirector.ServiceReference1.ISorting, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SortingClient : System.ServiceModel.ClientBase<RouteDirector.ServiceReference1.ISorting>, RouteDirector.ServiceReference1.ISorting {
        
        public SortingClient() {
        }
        
        public SortingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SortingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SortingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SortingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddBox(string barcode, int node, int line) {
            return base.Channel.AddBox(barcode, node, line);
        }
        
        public int AddBoxList(RouteDirector.ServiceReference1.Box[] boxList) {
            return base.Channel.AddBoxList(boxList);
        }
    }
}
